### ISSUE TITLE
Provide operator support for rotating "encryption at rest" keys

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#10]
While evaluating data encryption at rest it's not clear how to rotate encryption keys.
According this guide:
https://github.com/aerospike/aerospike-kubernetes-operator/wiki/Deploy-Aerospike-cluster#create-secrets
We can create secrets, but how to rorate them? Is this manual operation or operator will handle this? 
Can we keep such secrets in hashivault or this is out of scope for operator?

**Comment by arrowplum** [comment]
I think, but I am not sure, that we are mixing things up here. Do you mean encryption at rest as in https://www.aerospike.com/docs/operations/configure/security/encryption-at-rest/?

**Comment by vasilievip** [comment]
yes, correct

**Comment by sud82** [comment]
Currently operator can not handle encryption-at-rest feature. Whenever it will be provided, operator will handle it internally.
Currently we don't have any plan for hashivault.

**Comment by rbotzer** [comment]
Tracked internally in PROD-1262.

**Comment by rbotzer** [comment]
The main issue with rotating the encryption-at-rest key is described in [General process for adding, removing, or changing a key for all nodes](https://www.aerospike.com/docs/operations/configure/security/encryption-at-rest/#general-process-for-adding-removing-or-changing-a-key-for-all-nodes). This is what needs to be automated in the Operator. 

Getting a different key from something like Hashicorp Vault can happen outside of the Operator, using consulenv or one of the other techniques supported by Vault. Once you get the new key, you can call the Operator to rotate in the new secret.

**Comment by sud82** [comment]
Released in 2.1.
https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/2.1.0
