### ISSUE TITLE
Need 6.0.0 Support

### ISSUE THREAD

**Issue by adumovic** [aerospike/aerospike-kubernetes-operator#143]
I love the operator and it has simplified a lot of management for us, but i would also like to upgrade our various aerospike clusters to 6.0 to enable some of the new features. Now that i am on operator instead of manual helm charts for aerospike enterprise, this is impossible as operator validates versions and does not support greater than  5.7.x.x

**Comment by vlasenkoandrey** [comment]
I am in the same boat. In desperate need of Aerospike 6+ support

**Comment by sud82** [comment]
Released in 2.1.
https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/2.1.0
