### ISSUE TITLE
Support overriding alternate-access-address

### ISSUE THREAD

**Issue by thibautcharry** [aerospike/aerospike-kubernetes-operator#165]
As far I can understand, the `alternate-access-address` Aerospike configuration is supposed to be filled automatically to the public IP of the Kubernetes node by getting this IP from the node’s `node.status.addresses` field (address of type: `ExternalIP`).

However in our on-premise environment this field is not populated and there is no solution to get it populated, so the `alternate-access-address` is automatically set to the private IP of the node instead.
 
Is there a way to override `alternate-access-address` with the Aerospike Kubernetes Operator in order to set the proper public IP?
We could not find a way to do this, the operator always puts back the private IP in the configuration.

If not, could this be implemented in any way?

Thanks!

**Comment by tanmayja** [comment]
Hi @thibautcharry, could you explain a bit more about your use case regarding your on-premise setup and about network policy details used in aerospike cluster.
alternate-access-address is a per pod field and aerospike cluster CR is general for all pods. How are you planning to set alternate-access-address for individual pods. Apart from this Status.Pods fields are not meant to be set externally.

**Comment by arrowplum** [comment]
@thibautcharry could you give that extra description at a higher level of what you would like to accomplish here?

**Comment by a2chang** [comment]
@thibautcharry we are getting inquiries from Raymond and Younes regarding this issue.  Are you able to answer the questions from our developers so they can assess the situation?

**Comment by sud82** [comment]
Added this feature in 2.5.0 
https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/2.5.0#:~:text=%5BKO%20%2D200%5D%20%2D%20Allow%20ConfiguredIP%20in%20the%20CR%20NetworkPolicy.
