### ISSUE TITLE
Eample aerospike configs fail validation.

### ISSUE THREAD

**Issue by dwelch-spike** [aerospike/aerospike-kubernetes-operator#197]
Hi everyone, thanks for working on this and the management lib, both great projects!

I'm trying to use the IsValid() method from the management lib on the example configs from https://github.com/aerospike/aerospike-kubernetes-operator/tree/master/config/samples . I'm using schemas copied from https://github.com/aerospike/aerospike-kubernetes-operator/tree/master/pkg/configschema/json. After converting the yaml files to aerospike conf IsValid() is returning errors like... 

```
time="2023-03-09T11:48:36-08:00" level=error msg="valid is false" error="error while validating aerospike config" file=testdata/sources/all_flash_cluster_cr.yaml
time="2023-03-09T11:48:36-08:00" level=error msg=validationErrors Context="(root).network.heartbeat" Description="Must validate at least one schema (anyOf)" ErrType=number_any_of Field=network.heartbeat Value="{\"port\":3002}" error="error while validating aerospike config" file=testdata/sources/all_flash_cluster_cr.yaml
time="2023-03-09T11:48:36-08:00" level=error msg=validationErrors Context="(root).network.heartbeat" Description="mode is required" ErrType=required Field=network.heartbeat Value="{\"port\":3002}" error="error while validating aerospike config" file=testdata/sources/all_flash_cluster_cr.yaml
Error: config schema error
```

Do the example configs need fields like heartbeat mode added?

Thanks.

**Comment by tanmayja** [comment]
Hey @dwelch-spike, in Aerospike operator, mutating webhook fills up the required field in the config before checking for validation, all the samples yaml might not be directly useful and may fail the validation. If you need to use isValid without mutating web hook, you need to add the required fields in the config by checking in in json config schema.

**Comment by dwelch-spike** [comment]
Thanks @tanmayja, for now I've copied the schema files to asconfig and added the required fields. Closing.
