### ISSUE TITLE
Aerospike tools are not available

### ISSUE THREAD

**Issue by Siddhant-Thakuria** [aerospike/aerospike-kubernetes-operator#28]
Hey! When I tried to use this, I was unable to access the aerospike tools. Please do help me with this issue

**Comment by sud82** [comment]
@Siddhant-Thakuria Are you talking about this issue --> https://github.com/aerospike/aerospike-kubernetes-operator/issues/12
or is it something different? 

You can also use our tools image to connect to the cluster.
https://github.com/aerospike/aerospike-kubernetes-operator/wiki/Connect-to-the-Aerospike-cluster#with-asadm

**Comment by arrowplum** [comment]
Fixed with latest docker images.
