### ISSUE TITLE
k8sNodeBlockList with local persistent volume restart loop

### ISSUE THREAD

**Issue by noam-ma-ma** [aerospike/aerospike-kubernetes-operator#295]
Hey, I've tried using this feature as described here: https://aerospike.com/docs/cloud/kubernetes/operator/node-maintenance#k8snodeblocklist

I added a single node in order to test it, but the operator keeps killing the pod, without deleting the PVCs that were attached to this pod. Only after manually deleting the relevant PVC, the pod was able to start.
I'm using the Operator version 3.3.0, 2 node aerospike cluster with persistent local ssd storage (`volumes.[*].source.persistentVolume.storageClass: local-ssd`)

Am I missing something?

**Comment by tanmayja** [comment]
Hi @noam-ma-ma, please ensure that you've specified the local storage class name to the operator. This will enable AKO to delete the corresponding PVCs. Kindly verify that you have followed this step as outlined in the documentation.

> If the pods are using the local-attached storage, you must specify those local storage classes in the spec.Storage.LocalStorageClasses field of the CR. AKO uses this field to delete the corresponding local volumes so that the pods can be easily migrated out of the Kubernetes nodes.
