### ISSUE TITLE
k8sNodeBlockList support via Helm

### ISSUE THREAD

**Issue by mateusmuller** [aerospike/aerospike-kubernetes-operator#304]
Folks,

We are using the `aerospike-cluster` chart to create our aerospike cluster on k8s. This is very useful for our GitOps approach with Flux, since we can ensure that the cluster depends on the operator.

I'd like to add the `k8sNodeBlockList` but looks like this flag is not supported [here](https://github.com/aerospike/aerospike-kubernetes-operator/blob/master/helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml).

Is this expected or something we can add? I'll be happy to fire a PR for it.

Thanks!

**Comment by sud82** [comment]
@mateusmuller This looks like a bug. We will fix it. Thanks!

**Comment by mateusmuller** [comment]
@sud82 any updates on this? we'd like to use this with HelmRelease CRD from Flux and we're waiting for the chart to be modified, thanks!

**Comment by sud82** [comment]
> @sud82 any updates on this? we'd like to use this with HelmRelease CRD from Flux and we're waiting for the chart to be modified, thanks!

Hi @mateusmuller, It is fixed in the master. We will release it within 2-3 days.

**Comment by abhishekdwivedi3060** [comment]
Hi @mateusmuller, the latest 3.4 helm chart is available now with all the required fields. 
You can give it a try.
