### ISSUE TITLE
Error setting resources in helm values file

### ISSUE THREAD

**Issue by eb-koddi** [aerospike/aerospike-kubernetes-operator#42]
Should line 68 of deployment.yaml be nindent instead of indent?  YAML to JSON conversion error if I try to actually set the resources of the aerospike kubernetes operator with the helm chart via values file.

`
 {{- with .Values.resources }}
`
`resources: {{- toYaml . | indent 12 }}`
`{{- end }}
`

**Comment by eb-koddi** [comment]
I checked out the source, tested a values.yaml with resources being set, fails helm lint.  changed line 68 to nindent instead of indent, passes lint.

**Comment by spkesan** [comment]
Thanks @eb-koddi for reporting the issue and fixing it.
