### ISSUE TITLE
Allow to update running cluster configuration w/o restart of pods

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#49]
- Most of configs are dynamic and do not require restart
- Config file change (config map change?) can be detected and configs reloaded (via sending signal to aerospike process or by pushing config via api by operator)

**Comment by sud82** [comment]
We are working on it. This feature will be added in the next release.

**Comment by sagesheryl** [comment]
Fixed in Aerospike Kubernetes Operator 2.0 release.  
Tracking under PROD-1277 - Rapid restarts: The Operator should allow for warm start in the most scenarios.
