### ISSUE TITLE
Can't set custom docker registry to init container

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#5]
We use artifactory as caching proxy for docker registries in order to apply scanner and tolerate internet connectivity issues.
The docker registry appears to be hardcoded [controller_helper.go](https://github.com/aerospike/aerospike-kubernetes-operator/blob/2d276dc9ba2d109df14fdfff46eeadbd5aa5cbfb/pkg/controller/aerospikecluster/controller_helper.go#L167-L169)

Could you please make option configurable?

**Comment by sud82** [comment]
Hi @vasilievip, Thanks for feedback. We will try to make it configurable.

**Comment by jfwm2** [comment]
Hello @sud82 
Do you have any ETA on this feature?

**Comment by jfwm2** [comment]
Hopefully https://github.com/aerospike/aerospike-kubernetes-operator/pull/39 should do it

**Comment by sud82** [comment]
Released in 2.1.
https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/2.1.0
