### ISSUE TITLE
Need a way to add pod annotations to the operator created statefulset 

### ISSUE THREAD

**Issue by eb-koddi** [aerospike/aerospike-kubernetes-operator#56]
In order to use things like the datadog integration for aerospike, we need to be able to put (and keep) annotations on the aerospike statefulset pods. With the operator managing the pods, it would be optimal to be able to add pod annotations to the AerospikeCluster spec which get applied to the pods of the statefulset that gets created by the kubernetes operator.

**Comment by sud82** [comment]
This will be part of the next Operator release.

**Comment by arrowplum** [comment]
https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/2.0.0
