### ISSUE TITLE
Can't set additional annotations on the operator

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#6]
In our case, we want to test operator with Istio and we enable Istio globally per namespace AND we switch it on specific workload by annotations.
Please add the possibility to add  custom annotations to the statefullset

**Comment by arrowplum** [comment]
This makes a lot of sense. Thank you for taking the time to give feedback. Adding these to the feature request label.

**Comment by arrowplum** [comment]
Done with 2.0 release
