### ISSUE TITLE
There needs to be a way to pass nodeSelector settings to Operator managed Aerospike Clusters

### ISSUE THREAD

**Issue by eb-koddi** [aerospike/aerospike-kubernetes-operator#61]
We need to be able to pass nodeSelector settings to limit the deployment of Aerospike Cluster stateful sets to specific nodeSelector criteria matching node labels.

**Comment by sud82** [comment]
@eb-koddi This will be added in the next release.

**Comment by sud82** [comment]
This has been fixed.
