### ISSUE TITLE
Allow to configure if NodePort should be used

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#8]
In our environment, we don't use Kubernetes service NodePort.

Could you please make this  configurable?

**Comment by arrowplum** [comment]
It should just be MultiPodPerHost false I believe.

https://github.com/aerospike/aerospike-kubernetes-operator/blob/master/deploy/crds/aerospike.com_aerospikeclusters_crd.yaml#L121

Does that work for you?

**Comment by arrowplum** [comment]
In the docs it is over here: https://github.com/aerospike/aerospike-kubernetes-operator/wiki/Configuration#spec

**Comment by vasilievip** [comment]
oops, yes, sorry 
Thanks
