### ISSUE TITLE
Failure to scale up using rack and zone based node groups on EKS

### ISSUE THREAD

**Issue by eb-koddi** [aerospike/aerospike-kubernetes-operator#80]
Pods of the statefulset get stuck in Pending.

Events:
  Type     Reason             Age                 From                Message
  ----     ------             ----                ----                -------
  Warning  FailedScheduling   12s (x8 over 10m)   default-scheduler   0/12 nodes are available: 1 node(s) had volume node affinity conflict, 2 Insufficient memory, 2 node(s) didn't match node selector, 9 Insufficient cpu.
  Normal   NotTriggerScaleUp  10s (x18 over 10m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had volume node affinity conflict, 2 node(s) didn't match node selector

Looking at the pvc: 

Volumes:
  9afc3e6fc2c83f5b74b95be4c5d7c0-opt-aerospike-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  9afc3e6fc2c83f5b74b95be4c5d7c0-opt-aerospike-data-aerocluster-test-2-0
    ReadOnly:   false

Details on the pvc show that it is tied to us-west-2c:

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  creationTimestamp: "2021-09-15T04:58:31Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-west-2
    failure-domain.beta.kubernetes.io/zone: us-west-2c

but rack id 2 is supposed to be us-west-2b:
      - id: 2
        zone: us-west-2b
        aerospikeConfig:
          service:
            proto-fd-max: 18000
        storage:
          filesystemVolumePolicy:
            initMethod: deleteFiles
            cascadeDelete: true
          blockVolumePolicy:
            cascadeDelete: true
          volumes:
            - storageClass: ssd
              path: /opt/aerospike
              volumeMode: filesystem
              sizeInGB: 3

Looking at the actual pod of aerocluster-test-2-0 confirms that the pod itself was tied to the right zone, us-west-2b:

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - us-west-2b

I did some checking in the code for the statefulset controller, and I see where the Rack zone setting is picked up and applied, but can not find equivalent for the pvc.

The behavior being exhibited seems to match issues described here, under Problems section:

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-topology-scheduling.md

**Comment by sud82** [comment]
Hi @eb-koddi, Sorry for the late response. PVC does not have any scheduling policy fields. We should use WaitForFirstConsumer as volumeBindingMode in storageClass to ensure that PVC follows Pod's scheduling policies. 

https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

**Comment by arrowplum** [comment]
Closing as answered.
