### ISSUE TITLE
[PROD-2182] migrate-fill-delay unnecessarlily applied during scaling in.

### ISSUE THREAD

**Issue by skolosov-snap** [aerospike/aerospike-kubernetes-operator#93]
Context.
We have create (using Aerospike Kubernetes Operator) an empty cluster with 6 nodes with config containing **migrate-fill-delay=1800**.
Then we resized the cluster to 3 node. After removing of each node operator waits for migration to be over. Thus scaling down operation takes 1.5 hours (even for empty cluster).
Is it possible to ignore **migrate-fill-delay** parameter when we scaling down the cluster? We can see two options here:

1. Aerospike Kubernetes Operator can change **migrate-fill-delay** parameter to 0 before, before deleting the Pod. And after deleting the node set it back to original value.
    - The caveat part here is that if other node get restarted for some reason, that node will cause a migration which can be avoided.

2. To introduce new command in Aerospike Cluster: "**prepare-node-for-deletion**". This command will mark the node as node for deletion. And Aerospike Cluster will ignore **migrate-fill-delay** parameter for this node and also enable **Quiesce**  for that node.

**Comment by arrowplum** [comment]
This feature request is being tracked as PROD-2182

**Comment by arrowplum** [comment]
Plan as of our last discussion: 

Allow a field in crd to control an optional override for `migrate-fill-delay` to be used when scaling in. This could be used to cover this case where the delay is not wanted when scaling in (but is wanted in other cases)
